version: '3'
services:
  go:
    image: golang:1.19
    ports:
      - '8000:8000'
    command: go run main.go

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - .env

    ports:
      - '6000:27017'
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  mongodb:
  redisDB:

